### ISSUE TITLE
Suggestion: ktx2

### ISSUE THREAD

**Issue by MCCRegTech** [bghgary/glTF-Shell-Extensions#3]
Hi - Thanks for this extension

Sometimes getting GLB files with 'ktx2' (new Khronos compression type) - 'ktx2' is a container 

- https://doc.babylonjs.com/divingDeeper/materials/using/ktx2Compression
- http://github.khronos.org/KTX-Specification/

I wonder how easy to add this no image compression type

the message I get 'Unsupported mime type: image/ktx2'

Best,

Joe

**Comment by bghgary** [comment]
I'll look into it. Or if you are capable/willing to contribute a fix, that'll work too :)
